=== mfrailis/DAS/ddl/ddl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DAS Data Definition Layer  -->

<!-- The DAS DDL is a list of one or more data types. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://oats.inaf.it/das"
  targetNamespace="http://oats.inaf.it/das" elementFormDefault="qualified">
  <xs:element name="ddl">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="type"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!--
    A data type has zero or one ancestor, an arbitrary number of associated
    data types, a mandatory metadata section (if not inherited from an ancestor) 
    and an optional data section. 
  -->
  <xs:element name="type">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="associated"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="metadata" />
        <xs:element minOccurs="0" maxOccurs="1" ref="data" />
      </xs:sequence>       
      <xs:attribute name="name" use="required" type="xs:ID"/>
      <xs:attribute name="ancestor" type="xs:IDREF"  default="essentialMetadata"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>


  <!--
    A data type can have associated data types. Each association can be a 1 to 1 or
    a 1 to many relation
  -->
  <xs:element name="associated">
    <xs:complexType>
      <xs:attribute name="name" use="required"  type="xs:Name"/>
      <xs:attribute name="type" use="required" type="xs:IDREF"/>
      <xs:attribute name="multiplicity" default="one">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="one"/>
            <xs:enumeration value="many"/>
          </xs:restriction>  
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>
 
  <!--
    The metadata section defines a list of keywords
  -->
  <xs:element name="metadata">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="keyword"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <!--
    A keyword has a name, a type, a unit  and a description.  If a default value
    is set for a meta data, it will not be necessary to set explicitely a value
    for this meta data during runtime. A (database) index will be generated for a
    keyword if "index" is set to "yes", default "no".
  -->
  <xs:element name="keyword">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:Name"/>
      <xs:attribute name="description"/>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="byte"/>
            <xs:enumeration value="int16"/>
            <xs:enumeration value="int32"/>
            <xs:enumeration value="int64"/>
            <xs:enumeration value="float32"/>
            <xs:enumeration value="float64"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="char"/>
            <xs:enumeration value="string"/>
            <xs:enumeration value="text"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="unit" default="none"/>
      <xs:attribute name="default"/>
      <xs:attribute name="index" default="no">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="no"/>
            <xs:enumeration value="yes"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>


  <!--
    The data section defines either a binary table or an image. Both the image or
    the binary table can be stored as external files or as blobs within the database.
    The default is storing the data as external files.
  -->
  <xs:element name="data">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="1">
        <xs:element ref="binaryTable" />
        <xs:element ref="image" />
      </xs:choice>
      <xs:attribute name="storeAs" default="file">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="blob"/>
            <xs:enumeration value="file"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>      
    </xs:complexType>   
  </xs:element>
  
  <!--
    The binary table defines a list of columns
  --> 
  <xs:element name="binaryTable">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="column" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>  
 
  <!--
    A column has a name, a type, a unit  and a description. If the type of the column is string,
    then the maximum length of the string should be specified. The default value is 256.
  -->
  <xs:element name="column">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:Name"/>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="byte"/>
            <xs:enumeration value="int16"/>
            <xs:enumeration value="int32"/>
            <xs:enumeration value="int64"/>
            <xs:enumeration value="float32"/>
            <xs:enumeration value="float64"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="char"/>
            <xs:enumeration value="uint8"/>
            <xs:enumeration value="uint16"/>
            <xs:enumeration value="uint32"/>
            <xs:enumeration value="string"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="unit" default="none"/>
      <xs:attribute name="maxStringLength" type="xs:short" default="256"/>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>

  <!--
    The image provides a two dimensional array of pixels (data cubes are currently
    not considered). A pixel type must be specified. 
  --> 
  <xs:element name="image">
    <xs:complexType>
      <xs:attribute name="pixType" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="byte"/>
            <xs:enumeration value="int16"/>
            <xs:enumeration value="int32"/>
            <xs:enumeration value="float32"/>
            <xs:enumeration value="float64"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="description"/>
    </xs:complexType>
  </xs:element>


</xs:schema>

=== mfrailis/DAS/ddl/ddl_test_types.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc [
<!ENTITY das_essential SYSTEM "../resources/das_essential.xml">
]>
<ddl xmlns="http://oats.inaf.it/das"
     xmlns:xi="http://www.w3.org/2001/XInclude"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://oats.inaf.it/das ../resources/ddl.xsd">
    
    <!-- 
       DAS System types  
    -->    
    
    &das_essential;
    
    <!-- 
        User defined types
    -->  
    
    
    <!-- 
        Metadata for CIWS DPS measures
    -->      
    
    
    <type name="test_keywords">
        <metadata>
            <keyword name ="key_byte"    type="byte" />
            <keyword name ="key_int16"   type="int16" />
            <keyword name ="key_int32"   type="int32" />	
            <keyword name ="key_int64"   type="int64" />
            <keyword name ="key_float32" type="float32" />
            <keyword name ="key_float64" type="float64" />
            <keyword name ="key_boolean" type="boolean" />
            <keyword name ="key_char"    type="char" />
            <keyword name ="key_string"  type="string" />
            <keyword name ="key_text"    type="text" />
        </metadata>
    </type>
   
    <type name="test_associated_one_shared" ancestor="test_keywords"/> 
    <type name="test_association_one_shared">
        <associated name="association"
                  type="test_associated_one_shared"
                  multiplicity="one"
                  relation="shared"/>
    </type>


    <type name="test_associated_one_exclusive" ancestor="test_keywords"/>
    <type name="test_association_one_exclusive">
        <associated name="association"
                  type="test_associated_one_exclusive"
                  multiplicity="one"
                  relation="exclusive"/>
    </type>


    <type name="test_associated_many_shared" ancestor="test_keywords"/>
    <type name="test_association_many_shared">
        <associated name="association"
                  type="test_associated_many_shared"
                  multiplicity="many"
                  relation="shared"/>
    </type>


    <type name="test_associated_many_exclusive" ancestor="test_keywords"/>
    <type name="test_association_many_exclusive">
        <associated name="association"
                  type="test_associated_many_exclusive"
                  multiplicity="many"
                  relation="exclusive"/>
    </type>



    <type name="test_columns">
        <metadata>
            <keyword name ="sig_string"  type="int64" default="0"/>
            <keyword name ="dim_string"  type="int64" default="0"/>
            
            <keyword name ="sig_byte"    type="int64" default="0"/>
            <keyword name ="dim_byte"    type="int64" default="0"/>
            
            <keyword name ="sig_int16"   type="int64" default="0"/>
            <keyword name ="dim_int16"   type="int64" default="0"/>
            
            <keyword name ="sig_int32"   type="int64" default="0"/>
            <keyword name ="dim_int32"   type="int64" default="0"/>
            
            <keyword name ="sig_int64"   type="int64" default="0"/>
            <keyword name ="dim_int64"   type="int64" default="0"/>
            
            <keyword name ="sig_float32" type="float64" default="0"/>
            <keyword name ="dim_float32" type="int64" default="0"/>
            
            <keyword name ="sig_float64" type="float64" default="0"/>
            <keyword name ="dim_float64" type="int64" default="0"/>
            
            <keyword name ="sig_boolean" type="int64" default="0"/>
            <keyword name ="dim_boolean" type="int64" default="0"/>
            
            <keyword name ="sig_char"    type="int64" default="0"/>
            <keyword name ="dim_char"    type="int64" default="0"/>
            
            <keyword name ="sig_uint8"   type="int64" default="0"/>
            <keyword name ="dim_uint8"   type="int64" default="0"/>
            
            <keyword name ="sig_uint16"  type="int64" default="0"/>
            <keyword name ="dim_uint16"  type="int64" default="0"/>
            
            <keyword name ="sig_uint32"  type="int64" default="0"/>
            <keyword name ="dim_uint32"  type="int64" default="0"/>
        </metadata>
        <data>
            <binaryTable>
                <column name="column_string"  type="string"/>
                <column name="column_byte"    type="byte"/>
                <column name="column_int16"   type="int16"/>
                <column name="column_int32"   type="int32"/>
                <column name="column_int64"   type="int64"/>
                <column name="column_float32" type="float32"/>
                <column name="column_float64" type="float64"/>
                <column name="column_boolean" type="boolean"/>
                <column name="column_char"    type="char"/>
                <column name="column_uint8"   type="uint8"/>
                <column name="column_uin16"   type="uint16"/>
                <column name="column_uint32"  type="uint32"/>
            </binaryTable>
        </data>
    </type>

    <type name="test_columns_array">
        <metadata>
            <keyword name ="sig_string"  type="int64" default="0"/>
            <keyword name ="dim_string"  type="int64" default="0"/>
            
            <keyword name ="sig_byte"    type="int64" default="0"/>
            <keyword name ="dim_byte"    type="int64" default="0"/>
            
            <keyword name ="sig_int16"   type="int64" default="0"/>
            <keyword name ="dim_int16"   type="int64" default="0"/>
            
            <keyword name ="sig_int32"   type="int64" default="0"/>
            <keyword name ="dim_int32"   type="int64" default="0"/>
            
            <keyword name ="sig_int64"   type="int64" default="0"/>
            <keyword name ="dim_int64"   type="int64" default="0"/>
            
            <keyword name ="sig_float32" type="float64" default="0"/>
            <keyword name ="dim_float32" type="int64" default="0"/>
            
            <keyword name ="sig_float64" type="float64" default="0"/>
            <keyword name ="dim_float64" type="int64" default="0"/>
            
            <keyword name ="sig_boolean" type="int64" default="0"/>
            <keyword name ="dim_boolean" type="int64" default="0"/>
            
            <keyword name ="sig_char"    type="int64" default="0"/>
            <keyword name ="dim_char"    type="int64" default="0"/>
            
            <keyword name ="sig_uint8"   type="int64" default="0"/>
            <keyword name ="dim_uint8"   type="int64" default="0"/>
            
            <keyword name ="sig_uint16"  type="int64" default="0"/>
            <keyword name ="dim_uint16"  type="int64" default="0"/>
            
            <keyword name ="sig_uint32"  type="int64" default="0"/>
            <keyword name ="dim_uint32"  type="int64" default="0"/>
        </metadata>
        <data>
            <binaryTable>
                <column name="column_string"  type="string" arraysize="10"/>
                <column name="column_byte"    type="byte"   arraysize="10x5"/>
                <column name="column_int16"   type="int16"  arraysize="10x*"/>
                <column name="column_int32"   type="int32"  arraysize="10x5*"/>
                <column name="column_int64"   type="int64"  arraysize="*"/>
                <column name="column_float32" type="float32"/>
                <column name="column_float64" type="float64"/>
                <column name="column_boolean" type="boolean"/>
                <column name="column_char"    type="char"/>
                <column name="column_uint8"   type="uint8"/>
                <column name="column_uin16"   type="uint16"/>
                <column name="column_uint32"  type="uint32"/>
            </binaryTable>
        </data>
    </type>


    <type name="test_image2d">
        <data>
            <image pixType="float64"/>
        </data>
    </type>

    <type name="test_image3d">
        <data>
            <image pixType="float32" dimensions="3"/>
        </data>
    </type>

</ddl>

=== mfrailis/DAS/ddl/ddl_level1_types.xml
<?xml version="1.0" encoding="UTF-8"?>
<ddl xmlns="http://oats.inaf.it/das"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://oats.inaf.it/das ../resources/ddl.xsd">
 
    <!-- 
        Data type providing essential metadata. It shell be inherited (directly or indirecty)
        by all the other data types
    -->
    <type name="essentialMetadata" description="Provides common essential metadata information">
        <metadata>
            <keyword name="name" description="object name" type="string" index="yes"/>
            <keyword name="version" description="object version" type="int16" default="0"/>
            <keyword name="dbUserId" description="object creator" type="string"/>
            <keyword name="creationDate" type="int64" unit="s"/>
        </metadata>
    </type>
    
    <!-- 
        An example of a data type storing housekeeping timelines    
    -->
    <type name="lfiHkDaeSlowVoltage" description="DAE voltages - slow telemetry">
        <metadata>
            <keyword name="runId" type="string" description="test run ID (e.g. FUNC_0001)"/>
            <keyword name="startTime" description="start time of the timeline in UCT" type="int64" unit="ms"/>
            <keyword name="endTime" description="end time of the timeline in UCT" type="int64" unit="ms"/>
            <keyword name="APID" type="int16" description="application process ID of the source packet" default="1538"/>
            <keyword name="type" type="byte" description="type of the source packet" default="3"/>
            <keyword name="subtype" type="byte" description="subtype of the source packet" default="25"/>
            <keyword name="PI1_val" type="int16" description="source packet identifier from MIB - first" default="1"/>
            <keyword name="PI2_val" type="int16" description="source packet identifier from MIB - second" default="0"/>
        </metadata>
        <data>
            <binaryTable>
                <column name="sampleSCET" type="int64" unit="ms" description="sample time in UTC"/>
                <column name="LM151322Raw" type="uint16" unit="ADU" description="I1 LFI27 M1 - Raw value"/>
                <column name="LM151322Eng" type="float64" unit="V" description="I1 LFI27 M1 - Eng. value"/>
                <column name="LM151322Flag" type="int32" description="I1 LFI27 M1 - Flags"/>
                <column name="LM152322Raw" type="uint16" unit="ADU" description="I1 LFI27 M2 - Raw value"/>
                <column name="LM152322Eng" type="float64" unit="V" description="I1 LFI27 M2 - Eng. value"/>
                <column name="LM152322Flag" type="int32" description="I1 LFI27 M2 - Flags"/>                
            </binaryTable>
        </data>
    </type>
 
    <!-- 
        Data type to store images generated when producing the log of a test run   
    -->
    <type name="testLogImage">
        <metadata>
            <keyword name="naxis1" type="int32" description="image height"/>
            <keyword name="naxis2" type="int32" description="image width"/>
            <keyword name="format" type="string" description="e.g. jpeg, tiff, etc."/>
        </metadata>
        <data storeAs="blob">
            <image pixType="byte"/>
        </data>
    </type>
    
    <!-- 
        Data type to archive log information for a specific test run   
    -->    
    <type name="testLog">
        <associated name="images" type="testLogImage" multiplicity="many"/>
        <metadata>
            <keyword name="runId" type="string" description="test run ID (e.g. FUNC_0001)"/>
            <keyword name="startTime" type="int64" unit="ms" description="start time of the test run in UCT"/>
            <keyword name="endTime" type="int64" unit="ms" description="end time of the test run in UCT"/>
            <keyword name="log" type="text"/>
        </metadata>
    </type>
    
</ddl>

=== mfrailis/DAS/ddl/das_ddl_prototype2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc [
<!ENTITY das_essential SYSTEM "../resources/das_essential.xml">
]>
<ddl xmlns="http://oats.inaf.it/das" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://oats.inaf.it/das ../resources/ddl.xsd">

  &das_essential;

  <type name="s21"  description="ciws prototype data">
    <associated name="pdms" type="pdm" multiplicity="many" relation="exclusive"/>
    <metadata>
      <keyword name="dtelescopeid" description="telescope identifier" type="int16" index="yes" />
      <keyword name="dtype" description="packet type" type="int16"  index="yes" />
      <keyword name="dsubtype" description="packet sub type" type="int16" index="yes" />
      <keyword name="dssc" description="source sequence counter" type="int16"  index="yes" />
      <keyword name="datetime" type="string"  description="UTC date time yy-mm-ddThh:hh:ss" index="yes"/>
      <keyword name="nanoseconds" type="int32" unit="ns" description="nanoseconds fraction time" index="yes"/>
      <keyword name="gpsStatus" type="boolean" description="gps status" index="yes"/>
      <keyword name="eventnumber" type="int32" description="event number" index="yes" />
      <keyword name="configuration" type="string"  description="number of event" index="yes" />
      <keyword name="packetmode" type="int16" description="acquisition mode" index="yes" />
      <keyword name="npdm" type="int16"  description="number of pdms" index="yes" />
    </metadata>
  </type>

  <type name="pdm" description="pdm">
    <metadata>
      <keyword name="trpdm" type="boolean" description="triggered pdm id"  />
      <keyword name="id" type="int16"  description="pdm id"/>   
    </metadata>
    <data  storeAs="file">
      <binaryTable>
	<column name="HighGain" type="int16" unit="v" description="high gain values" arraysize="64" />
	<column name="LowGain" type="int16" unit="v" description="low gain values" arraysize="64" />
      </binaryTable>
    </data>
  </type>
</ddl>

=== mfrailis/DAS/ddl/schemas/benchmark.xml
<?xml version="1.0" encoding="UTF-8"?>
<ddl xmlns="http://oats.inaf.it/das"
 xmlns:xi="http://www.w3.org/2001/XInclude"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://oats.inaf.it/das ddl.xsd">

    <xi:include href="dasInstance.xml" parse="xml"
	xpointer="xmlns(das=http://oats.inaf.it/das)xpointer(//das:type[@name='essentialMetadata'])"/>

    <type name="TypeAnc">
        <metadata>
            <keyword name="timeStamp" type="int64" unit="ms" description="CPU timestamp"/>
            <keyword name="intkey" type="int32"/>
        </metadata>
    </type>
    
    <type name="assoc">
        <metadata>
            <keyword name="stringkey" type="string"/>
        </metadata>        
    </type>
    
    <type name="TypeMain" ancestor="TypeAnc">
        <associated name="one_ex"  type="oneEx"  multiplicity="one"  relation="exclusive"/>
        <associated name="one_sh"  type="oneSh"  multiplicity="one"  relation="shared"/>
        <associated name="many_ex" type="manyEx" multiplicity="many" relation="exclusive"/>
        <associated name="many_sh" type="manySh" multiplicity="many" relation="shared"/>
    </type>

    <type name="oneEx"  ancestor="TypeAnc">
        <associated name="nested_one_ex"  type="assoc"  multiplicity="one"  relation="exclusive"/>     
    </type>
    
    <type name="oneSh"  ancestor="TypeAnc">
        <associated name="nested_one_sh"  type="assoc"  multiplicity="one"  relation="shared"/>      
    </type>
    
    <type name="manyEx" ancestor="TypeAnc">
        <associated name="nested_many_ex" type="assoc" multiplicity="many" relation="exclusive"/>      
    </type>
    
    <type name="manySh" ancestor="TypeAnc"> 
        <associated name="nested_many_sh" type="assoc" multiplicity="many" relation="shared"/>   
    </type>
    
</ddl>
